<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IrdosarLog extends Model
{
    use HasFactory;
    protected $fillable = ['ID_Caz',
    'Nr_Dosar' ,
    'Nume_Debitor' ,
    'Prenume_Debitor' ,
    'CNP_CUI' ,
    'Adresa_Debitor' ,
    'Nume_Creditor' ,
    'Adresa_Creditor' ,
    'Titlu_Executoriu' ,
    'Data_Introducerii' ,
    'Suma_TotalaInitiala',
    'Suma_TotalaRamasa',
    'Suma_CreditorInitiala',
    'Suma_TrBEJ',
    'Suma_TrCreditor',
    'Procent_Onorariu',
    'Onorariu',
    'Taxa',
    'Cheltuieli',
    'Total_TrBEJ',
    'Suma_CreditorRamasa',
    'OnorariuTVA',
    'Total_BEJInitial',
    'Total_BEJRamas',
    'Firma_Debitor' ,
    'Adresa_Firma' ,
    'CoDebitor_Girant' ,
    'Stadiu_Dosar' ,
    'Data_Modificarii' ,
    'Data_Incasare' ,
    'Total_IncasariCreditor',
    'Total_IncasariBEJ',
    'Incasari_Totale',
    'DataEmitere_Interogare' ,
    'Poprire_Angajator' ,
    'Poprire_Conturi' ,
    'Valuta_Credit' ,
    'DataTitlu_Executoriu' ,
    'Suma_ValutaInitiala',
    'Suma_TrCreditorValuta',
    'Suma_ValutaRamasa',
    'Nume_Ex' ,
    'Suma_BEJValuta',
    'Cheltuieli_Valuta',
    'Taxa_Valuta',
    'Onorariu_TvaValuta',
    'Suma_trBEJValuta',
    'Suma_BEJValutaRamasa',
    'Ultima_Incasare',
    'BEJ_Incasat',
    'Creditor_Incasat',
    'BEJ_IncasatValuta',
    'Creditor_IncasatValuta',
    'Adresa_Ex' ,
    'Detalii_Ex' ,
    'Cont_Ex' ,
    'Oras_Ex' ,
    'Primarie_Debitor' ,
    'Ultima_IncasareValuta',
    'Incasari_TotaleValuta',
    'Sursa_Incasare' ,
    'Utilizator' ,
    'Comentarii' ,
    'ID_User' ,
    'ID_UserIncasare' ,
    'ID_UserComentarii' ,
    'Data_Comentariu' ,
    'ID_UserMod' ,
    'ID_UserEmInt' ,
    'Incasare_Nd',
    'Utilizator_recipise' ,
    'Incasare_NdData' ,
    'Suma_RamasaNd'];
}
